
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Advert {
/*
{
  "productId": 555,
  "productName": "聚租优品",
  "loanUpper": 11,
  "loanLower": 11,
  "applyNum": 1111,
  "productUrl":""
} 
*/

  int productId;
  String productName;
  String productUrl;
  String bannerImgUrl;
  int loanUpper;
  int loanLower;
  int applyNum;

  Advert({
    this.productId,
    this.productName,
    this.loanUpper,
    this.loanLower,
    this.applyNum,
    this.productUrl = null,
    this.bannerImgUrl = null,
  });
  Advert.fromJson(Map<String, dynamic> json) {
    productId = json['productId']?.toInt();
    productName = json['productName']?.toString();
    loanUpper = json['loanUpper']?.toInt();
    loanLower = json['loanLower']?.toInt();
    applyNum = json['applyNum']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['productId'] = productId;
    data['productName'] = productName;
    data['loanUpper'] = loanUpper;
    data['loanLower'] = loanLower;
    data['applyNum'] = applyNum;
    return data;
  }
}

