///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeRecommed {
/*
{
  "productId": 556,
  "loanUpper": 22,
  "loanLower": 11,
  "loanPeriodUpper": "12",
  "loanPeriodLower": "1",
  "loanSpeed": "1小时",
  "productDesc": "",
  "productName": "来租呗",
  "shortContent": "免押，热门",
  "applyNum": "0",
  "status": 1,
  "createTime": "Apr 28, 2023 6:13:50 PM",
  "productImgUrl": "https://rhyz.oss-cn-shenzhen.aliyuncs.com/product-20230428181304066.png"
} 
*/

  int productId;
  int loanUpper;
  int loanLower;
  String loanPeriodUpper;
  String loanPeriodLower;
  String loanSpeed;
  String productDesc;
  String productName;
  String shortContent;
  String applyNum;
  int status;
  String createTime;
  String productImgUrl;

  HomeRecommed({
    this.productId,
    this.loanUpper,
    this.loanLower,
    this.loanPeriodUpper,
    this.loanPeriodLower,
    this.loanSpeed,
    this.productDesc,
    this.productName,
    this.shortContent,
    this.applyNum,
    this.status,
    this.createTime,
    this.productImgUrl,
  });
  HomeRecommed.fromJson(Map<String, dynamic> json) {
    productId = json['productId']?.toInt();
    loanUpper = json['loanUpper']?.toInt();
    loanLower = json['loanLower']?.toInt();
    loanPeriodUpper = json['loanPeriodUpper']?.toString();
    loanPeriodLower = json['loanPeriodLower']?.toString();
    loanSpeed = json['loanSpeed']?.toString();
    productDesc = json['productDesc']?.toString();
    productName = json['productName']?.toString();
    shortContent = json['shortContent']?.toString();
    applyNum = json['applyNum']?.toString();
    status = json['status']?.toInt();
    createTime = json['createTime']?.toString();
    productImgUrl = json['productImgUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['productId'] = productId;
    data['loanUpper'] = loanUpper;
    data['loanLower'] = loanLower;
    data['loanPeriodUpper'] = loanPeriodUpper;
    data['loanPeriodLower'] = loanPeriodLower;
    data['loanSpeed'] = loanSpeed;
    data['productDesc'] = productDesc;
    data['productName'] = productName;
    data['shortContent'] = shortContent;
    data['applyNum'] = applyNum;
    data['status'] = status;
    data['createTime'] = createTime;
    data['productImgUrl'] = productImgUrl;
    return data;
  }
}
