
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserInfo {
/*
{
  "id": 1039806,
  "phoneNum": "13554757224",
  "smsCode": "0000",
  "smsCodeTime": "Apr 28, 2023 12:03:46 AM",
  "nickName": "李俊义",
  "idNum": "430703199012171113",
  "realNameVerify": 1,
  "realNameNeed": 0,
  "channelId": "aeb324a5e08f4ac0a6f25b1948ab60a8",
  "channelVisitTime": "Apr 28, 2023 12:03:46 AM",
  "userType": 1,
  "userAppType": 1,
  "coin": 0,
  "miId": "TJ202304281039806",
  "miScore": 0,
  "status": 0,
  "preSwitch": 1
} 
*/

  int id;
  String phoneNum;
  String smsCode;
  String smsCodeTime;
  String nickName;
  String idNum;
  int realNameVerify;
  int realNameNeed;
  String channelId;
  String channelVisitTime;
  int userType;
  int userAppType;
  int coin;
  String miId;
  int miScore;
  int status;
  int preSwitch;
  int vipLevel;
  UserInfo({
    this.id,
    this.phoneNum,
    this.smsCode,
    this.smsCodeTime,
    this.nickName,
    this.idNum,
    this.realNameVerify,
    this.realNameNeed,
    this.channelId,
    this.channelVisitTime,
    this.userType,
    this.userAppType,
    this.coin,
    this.miId,
    this.miScore,
    this.status,
    this.preSwitch,
    this.vipLevel = 1
  });
  UserInfo.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    phoneNum = json['phoneNum']?.toString();
    smsCode = json['smsCode']?.toString();
    smsCodeTime = json['smsCodeTime']?.toString();
    nickName = json['nickName']?.toString();
    idNum = json['idNum']?.toString();
    realNameVerify = json['realNameVerify']?.toInt();
    realNameNeed = json['realNameNeed']?.toInt();
    channelId = json['channelId']?.toString();
    channelVisitTime = json['channelVisitTime']?.toString();
    userType = json['userType']?.toInt();
    userAppType = json['userAppType']?.toInt();
    coin = json['coin']?.toInt();
    miId = json['miId']?.toString();
    miScore = json['miScore']?.toInt();
    status = json['status']?.toInt();
    preSwitch = json['preSwitch']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['phoneNum'] = phoneNum;
    data['smsCode'] = smsCode;
    data['smsCodeTime'] = smsCodeTime;
    data['nickName'] = nickName;
    data['idNum'] = idNum;
    data['realNameVerify'] = realNameVerify;
    data['realNameNeed'] = realNameNeed;
    data['channelId'] = channelId;
    data['channelVisitTime'] = channelVisitTime;
    data['userType'] = userType;
    data['userAppType'] = userAppType;
    data['coin'] = coin;
    data['miId'] = miId;
    data['miScore'] = miScore;
    data['status'] = status;
    data['preSwitch'] = preSwitch;
    return data;
  }
}



